### ISSUE TITLE
返回主页的图片不显示

### ISSUE THREAD

**Issue by liningit** [awescnb/awescnb#21]
![image](https://user-images.githubusercontent.com/3669213/133925113-c82b8ad9-bef6-458e-bd2d-2e94ef989210.png)

地址是https://api.uomg.com/api/rand.avatar

**Comment by guangzan** [comment]
目前请手动配置头像，不久将会自动获取头像，https://www.yuque.com/awescnb/user/rycpvv
![image](https://user-images.githubusercontent.com/43458667/134299222-85655cdd-ddb4-44dc-a332-fbef65b71812.png)
